// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjmdmhsbrdzrrlzxzeua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbWRtaHNicmR6cnJsenh6ZXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0OTI5NDcsImV4cCI6MjA5MDA2ODk0N30.kHiSQa9nt4H1NzoUZq1sA1PJ1_0Fg68bynYo1KYI7QA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
